name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow
      - wandb
      - ydata-profiling
      - matplotlib
      - pandas
      - numpy
      - seaborn
      - hydra-core
      - scikit-learn
      - jupyterlab
      - ipywidgets
