name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - requests
  - scikit-learn
  - pip:
      - mlflow
      - wandb
      - git+https://github.com/Fatimat01/short-term-rental-prices-ml-pipeline.git#egg=wandb-utils&subdirectory=components
