name: airbnb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - hydra-core
  - matplotlib
  - pandas
  - jupyterlab
  - cookiecutter
  - pip
  - pip:
      - mlflow
      - wandb