name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - requests
  - pandas
  - scikit-learn=1.7.2
  - pip:
      - mlflow
      - wandb
      - git+https://github.com/Fatimat01/short-term-rental-prices-ml-pipeline.git#egg=wandb-utils&subdirectory=components
