name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.12
  - pip:
      - mlflow
      - wandb
      - pandas
      - numpy
      - scikit-learn
      - hydra-core
